{"name": "test_create_order_invalid_data_server_error", "status": "passed", "steps": [{"name": "Create new order with non-existent hash: 4", "status": "passed", "start": 1725198351216, "stop": 1725198351453}], "start": 1725198351216, "stop": 1725198351455, "uuid": "334656af-d967-47dd-a6bb-f64f9bda2856", "historyId": "80772d84bd1a97ba37066f1be9a5b4b5", "testCaseId": "80772d84bd1a97ba37066f1be9a5b4b5", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_invalid_data_server_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "MacBook-Air-Elizaveta.local"}, {"name": "thread", "value": "84379-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}], "links": [{"type": "tms", "url": "Create new order with invalid data", "name": "Create new order with invalid data"}]}